name: Update Pinned Repositories

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows you to run manually

jobs:
  update-pinned-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Get Latest Repositories
        run: |
          curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/user/repos?sort=created&per_page=6" > repos.json

      - name: Update Profile README
        run: |
          echo "## 🚀 Latest Repositories" > README.md
          echo "" >> README.md
          jq -r '.[] | "- [\(.name)](\(.html_url))"' repos.json >> README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated pinned repositories"
          git push